-- Auto-generated by convert_audio.py
return {
  name = "Tenebre_Rosso_Sangue__ULTRAKILL_Original_Game_Soundtrack_",
  has_audio = "true",
  has_video = "false",
  duration = 233.93,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
