-- Auto-generated by convert_audio.py
return {
  name = "Fame_is_a_Gun",
  has_audio = "true",
  has_video = "false",
  duration = 183.48,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
