#!/usr/bin/env python3
"""
Convert local audio files into CC:Tweaked-ready DFPWM output.

Input layout:
  input/<song>.mp3

Output layout:
  output/<song>/audio.dfpwm
  output/<song>/manifest.lua
  output/index.lua

Requires ffmpeg and ffprobe on PATH.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
from pathlib import Path

SUPPORTED_EXTS = {".mp3", ".wav", ".flac", ".ogg", ".m4a", ".mp4"}


def sanitize_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_-]", "_", name)


def pcm_to_dfpwm(pcm_bytes: bytes) -> bytes:
    """Encode signed 8-bit PCM to DFPWM (CC:Tweaked-compatible)."""
    prec = 10
    prec_pow = 1 << prec
    prec_pow_half = 1 << (prec - 1)
    strength_min = 1 << (prec - 8 + 1)

    charge = 0
    strength = 0
    previous_bit = False
    previous_charge = 0
    out = bytearray()

    samples = list(pcm_bytes)
    while len(samples) % 8 != 0:
        samples.append(0)

    for i in range(0, len(samples), 8):
        byte_out = 0
        for j in range(8):
            sample = samples[i + j]
            if sample > 127:
                sample -= 256

            current_bit = sample > previous_charge or (sample == previous_charge and sample == 127)
            byte_out = (byte_out >> 1) | (128 if current_bit else 0)

            target = 127 if current_bit else -128
            next_charge = charge + (strength * (target - charge) + prec_pow_half) // prec_pow
            if next_charge == charge and next_charge != target:
                next_charge += 1 if current_bit else -1

            z = (prec_pow - 1) if (current_bit == previous_bit) else 0
            next_strength = strength
            if next_strength != z:
                next_strength += 1 if (current_bit == previous_bit) else -1
            if next_strength < strength_min:
                next_strength = strength_min

            charge = next_charge
            strength = next_strength
            previous_bit = current_bit
            previous_charge = next_charge

        out.append(byte_out)

    return bytes(out)


def ffprobe_duration_seconds(path: Path) -> float:
    result = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-show_entries",
            "format=duration",
            "-of",
            "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        capture_output=True,
        text=True,
    )
    try:
        return float(result.stdout.strip())
    except Exception:
        return 0.0


def convert_audio_to_dfpwm(input_path: Path, output_path: Path) -> float:
    duration = ffprobe_duration_seconds(input_path)

    ffmpeg = subprocess.run(
        [
            "ffmpeg",
            "-y",
            "-i",
            str(input_path),
            "-af",
            "pan=mono|c0=0.5*c0+0.5*c1,aresample=48000",
            "-ar",
            "48000",
            "-ac",
            "1",
            "-f",
            "s8",
            "pipe:1",
        ],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(pcm_to_dfpwm(ffmpeg.stdout))
    return duration


def write_manifest(path: Path, data: dict[str, object]) -> None:
    lines = ["-- Auto-generated by convert_audio.py", "return {"]
    for key, value in data.items():
        if isinstance(value, str):
            lines.append(f'  {key} = "{value}",')
        else:
            lines.append(f"  {key} = {value},")
    lines.append("}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_index(path: Path, audio_names: list[str]) -> None:
    lines = [
        "-- Auto-generated by convert_audio.py",
        "return {",
        "  video = {},",
        "  audio = {",
    ]
    for name in audio_names:
        lines.append(f'    "{name}",')
    lines += ["  },", "}"]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def discover_inputs(input_dir: Path) -> list[Path]:
    if not input_dir.exists():
        return []
    files = [p for p in input_dir.iterdir() if p.is_file() and p.suffix.lower() in SUPPORTED_EXTS]
    files.sort(key=lambda p: p.name.lower())
    return files


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert audio files into CC:Tweaked DFPWM output")
    parser.add_argument("--input", default="input", help="Input directory")
    parser.add_argument("--output", default="output", help="Output directory")
    args = parser.parse_args()

    input_dir = Path(args.input)
    output_dir = Path(args.output)

    source_files = discover_inputs(input_dir)
    if not source_files:
        print("No supported audio files found in input/.")
        return 0

    audio_names: list[str] = []

    for src in source_files:
        name = sanitize_name(src.stem)
        target_dir = output_dir / name
        audio_out = target_dir / "audio.dfpwm"
        manifest_out = target_dir / "manifest.lua"

        print(f"Converting: {src.name}")
        duration = convert_audio_to_dfpwm(src, audio_out)

        manifest = {
            "name": name,
            "has_audio": "true",
            "has_video": "false",
            "duration": round(duration, 2),
            "frame_count": 0,
            "fps": 0,
            "width": 0,
            "height": 0,
            "monitors_x": 0,
            "monitors_y": 0,
            "frame_ext": "",
        }
        write_manifest(manifest_out, manifest)
        audio_names.append(name)

    audio_names = sorted(set(audio_names), key=str.lower)
    write_index(output_dir / "index.lua", audio_names)

    print(f"Done. Converted {len(audio_names)} file(s).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
