-- Auto-generated by convert_audio.py
return {
  name = "The_Bones_Weep_For_You__TBOI_V1_MOD_ORIGINAL_SOUNDTRACK_",
  has_audio = "true",
  has_video = "false",
  duration = 170.57,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
