-- Auto-generated by convert_audio.py
return {
  name = "Forty_Six___2",
  has_audio = "true",
  has_video = "false",
  duration = 364.2,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
