-- Auto-generated by convert_audio.py
return {
  name = "TOKYO_HEAT__Tokyo_Drift_",
  has_audio = "true",
  has_video = "false",
  duration = 160.65,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
