-- Auto-generated by convert_audio.py
return {
  name = "Da_Kapa_Preta__K_Q__Remix_",
  has_audio = "true",
  has_video = "false",
  duration = 152.68,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
