-- Auto-generated by convert_audio.py
return {
  name = "Into_the_Fire",
  has_audio = "true",
  has_video = "false",
  duration = 241.03,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
