-- Auto-generated by convert_audio.py
return {
  name = "Kingslayer__feat__BABYMETAL_",
  has_audio = "true",
  has_video = "false",
  duration = 220.4,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
