-- Auto-generated by convert_audio.py
return {
  name = "My_Own_Summer__Shove_It_",
  has_audio = "true",
  has_video = "false",
  duration = 215.55,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
