-- Auto-generated by convert_audio.py
return {
  name = "The_Fire_Is_Gone__For_Music_Box_",
  has_audio = "true",
  has_video = "false",
  duration = 170.09,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
