-- Auto-generated by convert_audio.py
return {
  name = "The_Only_Thing_They_Fear_Is_You_Squared",
  has_audio = "true",
  has_video = "false",
  duration = 154.92,
  frame_count = 0,
  fps = 0,
  width = 0,
  height = 0,
  monitors_x = 0,
  monitors_y = 0,
  frame_ext = "",
}
